#!/usr/bin/env python3
import argparse
import json
import sys
from pathlib import Path

import boto3
from botocore.exceptions import BotoCoreError, ClientError

PRIVATE_IP_CONSUMING_TYPES = {"aws_instance", "aws_network_interface"}


def load_tfplan(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Terraform plan file not found: {path}")

    raw_bytes = path.read_bytes()
    text = None
    encoding_used = None

    for encoding in ("utf-8-sig", "utf-8", "utf-16"):
        try:
            text = raw_bytes.decode(encoding)
            encoding_used = encoding
            break
        except UnicodeDecodeError:
            continue

    if text is None:
        raise ValueError(
            f"Could not decode Terraform plan file {path} as UTF-8 or UTF-16"
        )

    print(
        f"DEBUG: loaded plan {path} with encoding={encoding_used} "
        f"(first bytes={raw_bytes[:4]!r})",
        file=sys.stderr,
    )

    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in Terraform plan file: {path}: {exc}") from exc


def count_private_ip_resources(plan: dict) -> int:
    if not isinstance(plan, dict):
        raise ValueError("Terraform plan JSON must be an object at the top level")

    resource_changes = plan.get("resource_changes")
    if resource_changes is None:
        raise ValueError("Terraform plan JSON missing 'resource_changes' section")
    if not isinstance(resource_changes, list):
        raise ValueError("Terraform plan JSON 'resource_changes' must be a list")

    count = 0
    for resource in resource_changes:
        if not isinstance(resource, dict):
            continue

        resource_type = resource.get("type")
        if resource_type not in PRIVATE_IP_CONSUMING_TYPES:
            continue

        change = resource.get("change", {})
        actions = change.get("actions", [])
        if "create" in actions:
            count += 1
            print(
                f"DEBUG: counted resource type={resource_type}, actions={actions}",
                file=sys.stderr,
            )

    print(f"DEBUG: total required private IP resources={count}", file=sys.stderr)
    return count


def get_subnet_available_ips(subnet_id: str) -> int:
    ec2 = boto3.client("ec2")
    print(f"DEBUG: describe_subnets called for SubnetIds=[{subnet_id}]", file=sys.stderr)
    try:
        response = ec2.describe_subnets(SubnetIds=[subnet_id])
    except (BotoCoreError, ClientError) as exc:
        raise RuntimeError(f"AWS EC2 describe_subnets failed: {exc}") from exc

    subnets = response.get("Subnets")
    print(f"DEBUG: describe_subnets response keys={list(response.keys())}", file=sys.stderr)
    if not subnets:
        raise RuntimeError(f"Subnet not found: {subnet_id}")

    subnet = subnets[0]
    available = subnet.get("AvailableIpAddressCount")
    print(
        f"DEBUG: subnet lookup returned id={subnet.get('SubnetId')} "
        f"AvailableIpAddressCount={available}",
        file=sys.stderr,
    )
    if available is None:
        raise RuntimeError("AWS response missing AvailableIpAddressCount")

    return int(available)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate whether a subnet has enough available private IPs for terraform planned resources."
    )
    parser.add_argument(
        "plan_file",
        type=Path,
        help="Path to Terraform plan JSON file generated by 'terraform show -json'.",
    )
    parser.add_argument(
        "subnet_id",
        type=str,
        help="AWS Subnet ID to query for available private IP addresses.",
    )
    parser.add_argument(
        "--override-required-ips",
        type=int,
        default=None,
        help="Optional override for the required private IP count, used only for simulation/testing.",
    )
    parser.add_argument(
        "--override-available-ips",
        type=int,
        default=None,
        help="Optional override for available private IP count, used only for simulation/testing.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        plan = load_tfplan(args.plan_file)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    try:
        required_ips = count_private_ip_resources(plan)
    except ValueError as exc:
        print(f"ERROR: invalid Terraform plan: {exc}", file=sys.stderr)
        return 1

    if args.override_required_ips is not None:
        print(
            f"DEBUG: overriding required IPs to {args.override_required_ips}",
            file=sys.stderr,
        )
        required_ips = args.override_required_ips

    if required_ips == 0:
        print(
            f"PASS: no private IP-consuming resources found in plan for subnet {args.subnet_id}."
        )
        return 0

    if args.override_available_ips is not None:
        print(
            f"DEBUG: overriding available IPs to {args.override_available_ips}",
            file=sys.stderr,
        )
        available_ips = args.override_available_ips
    else:
        try:
            available_ips = get_subnet_available_ips(args.subnet_id)
        except RuntimeError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1

    if available_ips < required_ips:
        deficit = required_ips - available_ips
        print(
            "FAILURE: insufficient available private IP addresses.",
            f"Subnet={args.subnet_id}",
            f"RequiredIPs={required_ips}",
            f"AvailableIPs={available_ips}",
            f"Deficit={deficit}",
        )
        print(
            "DETAILS: The terraform plan requests more private IP-consuming resources "
            "than the subnet can currently accommodate. Aborting build."
        )
        return 1

    print(
        "PASS: subnet has sufficient available private IP addresses.",
        f"Subnet={args.subnet_id}",
        f"RequiredIPs={required_ips}",
        f"AvailableIPs={available_ips}",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
